function toText(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return value.map(toText).filter(Boolean).join("; ");
  if (typeof value === "object") return Object.entries(value as Record<string, unknown>).map(([key, val]) => `${key}: ${toText(val)}`).join("; ");
  return String(value);
}
function toList(value: unknown): string[] { if (Array.isArray(value)) return value.map(toText).filter(Boolean); const item = toText(value); return item ? [item] : []; }
function Block({ title, items }: { title: string; items?: unknown }) { const rows = toList(items); return <div><strong>{title}</strong><ul style={{ lineHeight: 1.7, marginTop: 8 }}>{(rows.length ? rows : ["None listed."]).map((item, index) => <li key={index}>{item}</li>)}</ul></div>; }
function Field({ label, value }: { label: string; value: unknown }) { const text = toText(value); return text ? <p style={{ margin: "6px 0" }}><strong>{label}:</strong><br />{text}</p> : null; }
function DecisionTree({ record }: { record: any }) { const isCounty = Boolean(record.court_level || record.charge_category || record.final_client_decision || record.supervision_activity); const isNational = Boolean(record.source_confidence || record.accuracy_gate || record.source_confirmation_required); if (!isCounty && !isNational && !record.identity_match_status) return null; return <div className="card" style={{ background: "#f8fafc", marginTop: 14, padding: 14 }}><h4 style={{ margin: "0 0 8px" }}>{isCounty ? "County Crim Decision Tree" : "National Crim Decision Tree"}</h4><Field label="Identity Match" value={record.identity_match_status} /><Block title="Matched Identifiers" items={record.matched_identifiers} /><Block title="Missing Identifiers" items={record.missing_identifiers} /><Block title="Conflicting Identifiers" items={record.conflicting_identifiers} />{isCounty ? <><Field label="Court Level" value={record.court_level} /><Field label="Court Analysis" value={record.court_level_analysis} /><Field label="Charge Category" value={record.charge_category} /><Field label="Criminal Charge" value={record.criminal_charge} /><Field label="Disposition Category" value={record.disposition_category} /><Field label="Disposition Reportable" value={record.disposition_reportable} /><Field label="Duplicate Analysis" value={record.duplicate_analysis} /><Field label="Supervision Activity" value={record.supervision_activity} /><Field label="Age / Scope" value={record.age_scope_status} /><Field label="Final Client Decision" value={record.final_client_decision} /><Field label="Show to Client" value={record.show_to_client} /><Field label="Hide Reason" value={record.hide_reason} /><Field label="Manual Review Reason" value={record.manual_review_reason} /></> : <><Field label="Source Category" value={record.source_category} /><Field label="Source Confidence" value={record.source_confidence} /><Field label="Final Disposition" value={record.disposition_final} /><Field label="Duplicate Case Analysis" value={record.duplicate_case_analysis} /><Field label="Severity" value={record.severity_level} /><Field label="Accuracy Gate" value={record.accuracy_gate} /><Field label="Source Confirmation Required" value={record.source_confirmation_required} /><Field label="Suppress Reason" value={record.suppress_reason} /></>}</div>; }
function RecordReview({ record }: { record: any }) {
  return <section className="card" style={{ borderColor: "#cbd5e1", padding: 18 }}><h3 style={{ marginTop: 0 }}>{toText(record.record_title) || `Record ${toText(record.record_number)}`}</h3><Field label="Source" value={record.source} /><Field label="Name" value={record.name} /><Field label="Case" value={record.case_number} /><Field label="Court" value={record.court} /><Field label="County/State" value={record.county_state} /><Field label="Charge(s)" value={record.charges} /><Field label="Statute" value={record.statute} /><Field label="Offense Date" value={record.offense_date} /><Field label="File Date" value={record.file_date} /><Field label="Disposition Date" value={record.disposition_date} /><Field label="Status" value={record.status} /><DecisionTree record={record} /><p style={{ fontWeight: 900, marginTop: 14 }}>County Search Required: {toText(record.county_search_required) || "Needs review"}</p>{record.reportability_status ? <div className="card" style={{ background: "#f8fafc", marginTop: 14, padding: 14 }}><h4 style={{ margin: "0 0 8px" }}>Reportability</h4><p style={{ fontSize: 20, fontWeight: 900, margin: "0 0 8px" }}>{toText(record.reportability_status)}</p><Field label="7-Year Status" value={record.seven_year_status} /><Field label="Date Used" value={record.reportability_date_used} /><Field label="Outcome Type" value={record.disposition_type} /><Field label="Client Display" value={record.client_display} /><Field label="Exact Source Wording" value={record.exact_court_wording} /><Block title="Do Not Label As" items={record.do_not_label_as} /><Field label="Reason" value={record.reportability_reason} /></div> : null}<Block title="Why" items={record.why} /><Field label="Run" value={record.run} /><Field label="Decision" value={record.decision} /></section>;
}
export function AiResultView({ output, sources }: { output: any; sources?: any[] }) {
  if (!output) return <p style={{ color: "#5d687b" }}>No analysis result found.</p>;
  const recordReviews = Array.isArray(output.record_reviews) ? output.record_reviews : [];
  if (recordReviews.length) return <div style={{ display: "grid", gap: 22 }}><h2 style={{ margin: 0 }}>MATCH / COUNTY SEARCH REVIEW</h2><div><strong>Subject Name</strong><ul style={{ lineHeight: 1.7 }}>{toList(output.subject_names || output.subject_name || output.names_reviewed).length ? toList(output.subject_names || output.subject_name || output.names_reviewed).map((name, index) => <li key={index}>{name}</li>) : <li>See pasted name information below.</li>}</ul></div>{output.reportability_policy ? <section className="card" style={{ background: "#f8fafc", padding: 16 }}><strong>SaffHire Reportability Policy</strong><p style={{ lineHeight: 1.6 }}>{toText(output.reportability_policy)}</p><Block title="Reportability Summary" items={output.reportability_summary} /></section> : null}{recordReviews.map((record: any, index: number) => <RecordReview key={index} record={{ ...record, record_number: record.record_number || index + 1 }} />)}<section className="card" style={{ padding: 18 }}><h3 style={{ marginTop: 0 }}>FCRA Analysis</h3><Field label="Identity Strength" value={output.identity_strength} /><Block title="Concerns" items={output.identity_match_concerns} /></section><section className="card" style={{ padding: 18 }}><h3 style={{ marginTop: 0 }}>Final Summary</h3><Block title="Summary" items={output.final_summary} /><Block title="Run" items={output.overall_run} /><Block title="Do Not Run" items={output.overall_do_not_run} /><Block title="Priority" items={output.priority_order} /><p><strong>County verification needed:</strong> {output.county_verification_needed ? "Yes" : "No"}</p><p><strong>Supervisor review needed:</strong> {output.supervisor_review_needed ? "Yes" : "No"}</p><p><strong>Confidence:</strong> {typeof output.confidence === "number" ? `${Math.round(output.confidence * 100)}%` : toText(output.confidence) || "Not provided"}</p></section><div><strong>Draft Reviewer Note</strong><pre style={{ background: "#f8fafc", borderRadius: 12, padding: 16, whiteSpace: "pre-wrap" }}>{toText(output.draft_reviewer_note) || "No draft note provided."}</pre></div>{sources?.length ? <div><strong>Source Excerpts</strong>{sources.map((source: any) => <pre key={source.id || source.source_label} style={{ background: "#f8fafc", borderRadius: 12, padding: 12, whiteSpace: "pre-wrap" }}>{toText(source.source_label)}\n{toText(source.source_excerpt)}</pre>)}</div> : null}</div>;
  return <div style={{ display: "grid", gap: 18 }}><div><strong>Review Summary</strong><p style={{ lineHeight: 1.6 }}>{toText(output.review_summary) || "No summary provided."}</p></div>{output.client_display_recommendation ? <div className="card" style={{ background: "#f8fafc", borderColor: "#0f3b5f", padding: 16 }}><strong>Client Display Recommendation</strong><p style={{ lineHeight: 1.6 }}>{toText(output.client_display_recommendation)}</p></div> : null}<div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 18 }}><Block title="Records to Show Client" items={output.records_to_show_client} /><Block title="Records to Hold Back" items={output.records_to_hold_back} /><Block title="Identity / Match Concerns" items={output.identity_match_concerns} /><Block title="Record Completeness" items={output.record_completeness} /><Block title="Possible Reportability Issues" items={output.possible_reportability_issues} /><Block title="Possible Compliance Concerns" items={output.possible_fcra_concerns} /><Block title="Missing Information" items={output.missing_information} /><Block title="Sources Used" items={output.sources_used} /></div><div className="card" style={{ background: "#f8fafc", padding: 16 }}><strong>Recommended Next Step</strong><p>{toText(output.recommended_next_step) || "Not provided."}</p><p><strong>County verification needed:</strong> {output.county_verification_needed ? "Yes" : "No"}</p><p><strong>Supervisor review needed:</strong> {output.supervisor_review_needed ? "Yes" : "No"}</p><p><strong>Confidence:</strong> {typeof output.confidence === "number" ? `${Math.round(output.confidence * 100)}%` : toText(output.confidence) || "Not provided"}</p></div><div><strong>Draft Reviewer Note</strong><pre style={{ background: "#f8fafc", borderRadius: 12, padding: 16, whiteSpace: "pre-wrap" }}>{toText(output.draft_reviewer_note) || "No draft note provided."}</pre></div>{sources?.length ? <div><strong>Source Excerpts</strong>{sources.map((source: any) => <pre key={source.id || source.source_label} style={{ background: "#f8fafc", borderRadius: 12, padding: 12, whiteSpace: "pre-wrap" }}>{toText(source.source_label)}\n{toText(source.source_excerpt)}</pre>)}</div> : null}</div>;
}
