function toText(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return value.map(toText).filter(Boolean).join("; ");
  if (typeof value === "object") return Object.entries(value as Record<string, unknown>).map(([key, val]) => `${key}: ${toText(val)}`).join("; ");
  return String(value);
}
function toList(value: unknown): string[] { if (Array.isArray(value)) return value.map(toText).filter(Boolean); const item = toText(value); return item ? [item] : []; }
function Block({ title, items }: { title: string; items?: unknown }) { const rows = toList(items); return <div><strong>{title}</strong><ul style={{ lineHeight: 1.7, marginTop: 8 }}>{(rows.length ? rows : ["None listed."]).map((item, index) => <li key={index}>{item}</li>)}</ul></div>; }
function Field({ label, value }: { label: string; value: unknown }) { const text = toText(value); return text ? <p style={{ margin: "6px 0" }}><strong>{label}:</strong><br />{text}</p> : null; }
function DecisionBadge({ value }: { value: unknown }) { const text = toText(value) || "Needs review"; return <span style={{ background: "#e8f3ee", border: "1px solid #167f49", borderRadius: 999, color: "#0f5132", display: "inline-block", fontWeight: 900, padding: "6px 10px" }}>{text}</span>; }
function yesNo(value: unknown) { const text = toText(value).toLowerCase(); if (["true", "yes", "run", "required", "needed"].includes(text)) return "Yes"; if (["false", "no", "do not run", "not required", "not needed"].includes(text)) return "No"; return toText(value) || "Needs review"; }
function firstText(...values: unknown[]) { for (const value of values) { const text = toText(value); if (text) return text; } return ""; }
function caseNumber(record: any) { return firstText(record.case_number, record.case, record.caseNumber, record.cause_number, record.citation_number, record.docket_number); }
function recordTitle(record: any) { const base = firstText(record.record_title, record.recordTitle, record.source, `Record ${toText(record.record_number)}`); const name = firstText(record.name, record.subject_name, record.subject); const caseNo = caseNumber(record); const titleParts = [base, name].filter(Boolean); const title = titleParts.join(" - "); return caseNo ? `${title} - Case # ${caseNo}` : title; }
function countyToRun(record: any) { return firstText(record.county_to_run, record.county_state, record.county, record.jurisdiction, record.court); }
function shortReason(record: any) { const why = Array.isArray(record.why) ? record.why[0] : record.why; return firstText(why, record.decision, record.suppress_reason, record.manual_review_reason, record.address_or_geography_match, record.identity_match_status); }
function NationalIdentityReview({ record }: { record: any }) { return <div className="card" style={{ background: "#f8fafc", borderColor: "#0f3b5f", marginTop: 14, padding: 14 }}><h4 style={{ margin: "0 0 8px" }}>National Crim Identity / County Search Review</h4><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 12 }}><Field label="Searched Identity Facts" value={record.searched_identity_facts} /><Field label="Record Identity Facts" value={record.record_identity_facts} /><Field label="Alias / Name Variation" value={record.alias_or_name_variation} /><Field label="Address / Geography Match" value={record.address_or_geography_match} /></div><Field label="Identity Match Status" value={record.identity_match_status} /><Block title="Matched Identifiers" items={record.matched_identifiers} /><Block title="Missing Identifiers" items={record.missing_identifiers} /><Block title="Conflicting Identifiers" items={record.conflicting_identifiers} /><Field label="Source Category" value={record.source_category} /><Field label="Source Confidence" value={record.source_confidence} /><Field label="Final Disposition" value={record.disposition_final} /><Field label="Duplicate Case Analysis" value={record.duplicate_case_analysis} /><Field label="Severity" value={record.severity_level} /><Field label="Accuracy Gate" value={record.accuracy_gate} /><Field label="Source Confirmation Required" value={record.source_confirmation_required} /><Field label="Suppress Reason" value={record.suppress_reason} /></div>; }
function DecisionTree({ record }: { record: any }) { const isCounty = Boolean(record.court_level || record.charge_category || record.final_client_decision || record.supervision_activity); const isNational = Boolean(record.searched_identity_facts || record.record_identity_facts || record.source_confidence || record.accuracy_gate || record.source_confirmation_required); if (!isCounty && !isNational && !record.identity_match_status) return null; if (isNational && !isCounty) return <NationalIdentityReview record={record} />; return <div className="card" style={{ background: "#f8fafc", marginTop: 14, padding: 14 }}><h4 style={{ margin: "0 0 8px" }}>County Crim Decision Tree</h4><Field label="Identity Match" value={record.identity_match_status} /><Block title="Matched Identifiers" items={record.matched_identifiers} /><Block title="Missing Identifiers" items={record.missing_identifiers} /><Block title="Conflicting Identifiers" items={record.conflicting_identifiers} /><Field label="Court Level" value={record.court_level} /><Field label="Court Analysis" value={record.court_level_analysis} /><Field label="Charge Category" value={record.charge_category} /><Field label="Criminal Charge" value={record.criminal_charge} /><Field label="Disposition Category" value={record.disposition_category} /><Field label="Disposition Reportable" value={record.disposition_reportable} /><Field label="Duplicate Analysis" value={record.duplicate_analysis} /><Field label="Supervision Activity" value={record.supervision_activity} /><Field label="Age / Scope" value={record.age_scope_status} /><Field label="Final Client Decision" value={record.final_client_decision} /><Field label="Show to Client" value={record.show_to_client} /><Field label="Hide Reason" value={record.hide_reason} /><Field label="Manual Review Reason" value={record.manual_review_reason} /></div>; }
function RecordSummaryCard({ record }: { record: any }) { const runCounty = yesNo(record.county_search_required || record.run); const county = countyToRun(record); return <section className="card" style={{ background: "#fff", borderColor: "#b8c7da", padding: 16 }}><h3 style={{ margin: "0 0 12px" }}>{recordTitle(record)}</h3><p style={{ margin: "6px 0" }}><strong>Run County:</strong> {runCounty}</p>{runCounty.toLowerCase() === "yes" && county ? <p style={{ margin: "6px 0" }}><strong>County to run:</strong> {county}</p> : null}<p style={{ margin: "6px 0" }}><strong>Reason:</strong> {shortReason(record) || "Needs review."}</p></section>; }
function RecordReview({ record }: { record: any }) {
  const isNational = Boolean(record.searched_identity_facts || record.record_identity_facts || record.alias_or_name_variation || record.address_or_geography_match);
  return <section className="card" style={{ borderColor: "#cbd5e1", padding: 18 }}><h3 style={{ marginTop: 0 }}>{recordTitle(record)}</h3><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 12 }}><Field label="Source" value={record.source} /><Field label="Name" value={record.name} /><Field label="Case" value={caseNumber(record)} /><Field label="Court" value={record.court} /><Field label="County/State" value={record.county_state} /></div><Field label="Charge(s)" value={record.charges} /><Field label="Statute" value={record.statute} /><Field label="Offense Date" value={record.offense_date} /><Field label="File Date" value={record.file_date} /><Field label="Disposition Date" value={record.disposition_date} /><Field label="Status" value={record.status} /><DecisionTree record={record} /><div className="card" style={{ background: isNational ? "#f0f9ff" : "#f8fafc", borderColor: isNational ? "#7dd3fc" : "#cbd5e1", marginTop: 14, padding: 14 }}><p style={{ fontWeight: 900, marginTop: 0 }}>County Search Required: <DecisionBadge value={record.county_search_required} /></p><Block title="Why" items={record.why} /><Field label="Run" value={record.run} /><Field label="Decision" value={record.decision} /></div>{record.reportability_status ? <div className="card" style={{ background: "#f8fafc", marginTop: 14, padding: 14 }}><h4 style={{ margin: "0 0 8px" }}>Reportability</h4><p style={{ fontSize: 20, fontWeight: 900, margin: "0 0 8px" }}>{toText(record.reportability_status)}</p><Field label="7-Year Status" value={record.seven_year_status} /><Field label="Date Used" value={record.reportability_date_used} /><Field label="Outcome Type" value={record.disposition_type} /><Field label="Client Display" value={record.client_display} /><Field label="Exact Source Wording" value={record.exact_court_wording} /><Block title="Do Not Label As" items={record.do_not_label_as} /><Field label="Reason" value={record.reportability_reason} /></div> : null}</section>;
}
export function AiResultView({ output, sources }: { output: any; sources?: any[] }) {
  if (!output) return <p style={{ color: "#5d687b" }}>No analysis result found.</p>;
  const recordReviews = Array.isArray(output.record_reviews) ? output.record_reviews : [];
  if (recordReviews.length) return <div style={{ display: "grid", gap: 22 }}><h2 style={{ margin: 0 }}>MATCH / COUNTY SEARCH REVIEW</h2><div><strong>Subject Name / Aliases Found</strong><ul style={{ lineHeight: 1.7 }}>{toList(output.subject_names || output.subject_name || output.names_reviewed).length ? toList(output.subject_names || output.subject_name || output.names_reviewed).map((name, index) => <li key={index}>{name}</li>) : <li>See pasted name information below.</li>}</ul></div>{output.reportability_policy ? <section className="card" style={{ background: "#f8fafc", padding: 16 }}><strong>SaffHire Reportability Policy</strong><p style={{ lineHeight: 1.6 }}>{toText(output.reportability_policy)}</p><Block title="Reportability Summary" items={output.reportability_summary} /></section> : null}<section className="card" style={{ background: "#f8fafc", borderColor: "#0f3b5f", padding: 18 }}><h3 style={{ marginTop: 0 }}>Brief County Search Summary</h3><div style={{ display: "grid", gap: 12 }}>{recordReviews.map((record: any, index: number) => <RecordSummaryCard key={index} record={{ ...record, record_number: record.record_number || index + 1 }} />)}</div></section>{recordReviews.map((record: any, index: number) => <RecordReview key={index} record={{ ...record, record_number: record.record_number || index + 1 }} />)}<section className="card" style={{ padding: 18 }}><h3 style={{ marginTop: 0 }}>Identity / Match Summary</h3><Field label="Identity Strength" value={output.identity_strength} /><Block title="Concerns" items={output.identity_match_concerns} /></section><section className="card" style={{ padding: 18 }}><h3 style={{ marginTop: 0 }}>Final Summary</h3><Block title="Summary" items={output.final_summary} /><Block title="Run" items={output.overall_run} /><Block title="Do Not Run" items={output.overall_do_not_run} /><Block title="Priority" items={output.priority_order} /><p><strong>County verification needed:</strong> {output.county_verification_needed ? "Yes" : "No"}</p><p><strong>Supervisor review needed:</strong> {output.supervisor_review_needed ? "Yes" : "No"}</p><p><strong>Confidence:</strong> {typeof output.confidence === "number" ? `${Math.round(output.confidence * 100)}%` : toText(output.confidence) || "Not provided"}</p></section><div><strong>Draft Reviewer Note</strong><pre style={{ background: "#f8fafc", borderRadius: 12, padding: 16, whiteSpace: "pre-wrap" }}>{toText(output.draft_reviewer_note) || "No draft note provided."}</pre></div>{sources?.length ? <div><strong>Source Excerpts</strong>{sources.map((source: any) => <pre key={source.id || source.source_label} style={{ background: "#f8fafc", borderRadius: 12, padding: 12, whiteSpace: "pre-wrap" }}>{toText(source.source_label)}\n{toText(source.source_excerpt)}</pre>)}</div> : null}</div>;
  return <div style={{ display: "grid", gap: 18 }}><div><strong>Review Summary</strong><p style={{ lineHeight: 1.6 }}>{toText(output.review_summary) || "No summary provided."}</p></div>{output.client_display_recommendation ? <div className="card" style={{ background: "#f8fafc", borderColor: "#0f3b5f", padding: 16 }}><strong>Client Display Recommendation</strong><p style={{ lineHeight: 1.6 }}>{toText(output.client_display_recommendation)}</p></div> : null}<div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 18 }}><Block title="Records to Show Client" items={output.records_to_show_client} /><Block title="Records to Hold Back" items={output.records_to_hold_back} /><Block title="Identity / Match Concerns" items={output.identity_match_concerns} /><Block title="Record Completeness" items={output.record_completeness} /><Block title="Possible Reportability Issues" items={output.possible_reportability_issues} /><Block title="Possible Compliance Concerns" items={output.possible_fcra_concerns} /><Block title="Missing Information" items={output.missing_information} /><Block title="Sources Used" items={output.sources_used} /></div><div className="card" style={{ background: "#f8fafc", padding: 16 }}><strong>Recommended Next Step</strong><p>{toText(output.recommended_next_step) || "Not provided."}</p><p><strong>County verification needed:</strong> {output.county_verification_needed ? "Yes" : "No"}</p><p><strong>Supervisor review needed:</strong> {output.supervisor_review_needed ? "Yes" : "No"}</p><p><strong>Confidence:</strong> {typeof output.confidence === "number" ? `${Math.round(output.confidence * 100)}%` : toText(output.confidence) || "Not provided"}</p></div><div><strong>Draft Reviewer Note</strong><pre style={{ background: "#f8fafc", borderRadius: 12, padding: 16, whiteSpace: "pre-wrap" }}>{toText(output.draft_reviewer_note) || "No draft note provided."}</pre></div>{sources?.length ? <div><strong>Source Excerpts</strong>{sources.map((source: any) => <pre key={source.id || source.source_label} style={{ background: "#f8fafc", borderRadius: 12, padding: 12, whiteSpace: "pre-wrap" }}>{toText(source.source_label)}\n{toText(source.source_excerpt)}</pre>)}</div> : null}</div>;
}
