import { AppHeader } from "@/components/AppHeader";
import { requireUser } from "@/lib/session";
import { listDashboardUsers } from "@/lib/users";

export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<{ error?: string; created?: string; updated?: string }> }) {
  const user = await requireUser(["admin"]);
  const params = await searchParams;
  const users = await listDashboardUsers();
  return <><AppHeader user={user} /><main className="container-shell"><h1 style={{ marginTop: 0 }}>Admin Users</h1><p style={{ color: "#5d687b" }}>Add staff users who can access the private SaffHire Dashboard. Existing ENV admin users are shown but cannot be changed here.</p>{params.created ? <p style={{ color: "#167f49", fontWeight: 700 }}>User added.</p> : null}{params.updated ? <p style={{ color: "#167f49", fontWeight: 700 }}>User status updated.</p> : null}{params.error ? <p style={{ color: "#b42318", fontWeight: 700 }}>The user change could not be saved. Check that the email is unique and all fields are complete.</p> : null}<section className="card" style={{ padding: 22, marginBottom: 18 }}><h2 style={{ marginTop: 0 }}>Add User</h2><form action="/api/admin/users/create" method="post" style={{ display: "grid", gap: 14 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14 }}><label><span className="field-label">Name</span><input className="field-input" name="name" required /></label><label><span className="field-label">Email</span><input className="field-input" name="email" type="email" required /></label><label><span className="field-label">Role</span><select className="field-input" name="role" required><option value="reviewer">Reviewer</option><option value="supervisor">Supervisor</option><option value="admin">Admin</option></select></label><label><span className="field-label">Access Code</span><input className="field-input" name="accessCode" type="password" required minLength={6} /></label></div><button className="btn-primary" type="submit">Add User</button></form></section><section className="card" style={{ padding: 22 }}><h2 style={{ marginTop: 0 }}>Current Users</h2><div style={{ overflowX: "auto" }}><table style={{ borderCollapse: "collapse", width: "100%" }}><thead><tr><th align="left">Name</th><th align="left">Email</th><th align="left">Role</th><th align="left">Status</th><th align="left">Source</th><th align="left">Action</th></tr></thead><tbody>{users.map((row) => { const envUser = row.id.startsWith("env-"); return <tr key={row.id} style={{ borderTop: "1px solid #e5e7eb" }}><td style={{ padding: "10px 8px" }}>{row.name}</td><td style={{ padding: "10px 8px" }}>{row.email}</td><td style={{ padding: "10px 8px" }}>{row.role}</td><td style={{ padding: "10px 8px" }}>{row.is_active ? "Active" : "Inactive"}</td><td style={{ padding: "10px 8px" }}>{envUser ? "Vercel ENV" : "Admin page"}</td><td style={{ padding: "10px 8px" }}>{envUser ? <span style={{ color: "#5d687b" }}>ENV managed</span> : <form action="/api/admin/users/status" method="post"><input type="hidden" name="id" value={row.id} /><input type="hidden" name="isActive" value={row.is_active ? "false" : "true"} /><button className="btn-secondary" type="submit">{row.is_active ? "Deactivate" : "Activate"}</button></form>}</td></tr>; })}</tbody></table></div></section></main></>;
}
