import Link from "next/link";
import { AppHeader } from "@/components/AppHeader";
import { getTazworksStatus, listTazworksPayloads } from "@/lib/tazworks";
import { requireUser } from "@/lib/session";

export default async function TazworksPage({ searchParams }: { searchParams: Promise<{ connected?: string; error?: string; imported?: string }> }) {
  const user = await requireUser(["admin", "supervisor"]);
  const params = await searchParams;
  const status = getTazworksStatus();
  const payloads = await listTazworksPayloads();
  return <><AppHeader user={user} /><main className="container-shell"><h1 style={{ marginTop: 0 }}>TazWorks Sandbox Prep</h1><p style={{ color: "#5d687b" }}>Phase 1E adds safe preparation tools only. No production TazWorks pull is active yet.</p>{params.connected ? <p style={{ color: "#167f49", fontWeight: 700 }}>Connection settings are present.</p> : null}{params.imported ? <p style={{ color: "#167f49", fontWeight: 700 }}>Sample payload imported.</p> : null}{params.error ? <p style={{ color: "#b42318", fontWeight: 700 }}>TazWorks action failed. Review settings or JSON format.</p> : null}<section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(230px, 1fr))", gap: 16, marginBottom: 22 }}><div className="card" style={{ padding: 18 }}><strong>Connection Status</strong><p>{status.configured ? "Configured" : "Not fully configured"}</p></div><div className="card" style={{ padding: 18 }}><strong>Mode</strong><p>{status.sandboxMode ? "Sandbox" : "Production flag is off"}</p></div><div className="card" style={{ padding: 18 }}><strong>Base URL</strong><p>{status.baseUrlSet ? "Set" : "Missing"}</p></div><div className="card" style={{ padding: 18 }}><strong>Credentials</strong><p>{status.clientIdSet && status.clientSecretSet ? "Set" : "Missing"}</p></div></section><section className="card" style={{ display: "grid", gap: 14, marginBottom: 22, padding: 22 }}><h2 style={{ margin: 0 }}>Sandbox Actions</h2><div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}><form action="/api/tazworks/test-connection" method="post"><button className="btn-secondary" type="submit">Test Sandbox Settings</button></form><Link className="btn-primary" href="/tazworks/import">Import Sample JSON</Link><Link className="btn-muted" href="/tazworks/mapping">View Field Mapping</Link></div></section><section className="card table-wrap"><table><thead><tr><th>Imported</th><th>Applicant</th><th>DOB</th><th>Report ID</th><th>Records</th><th>Action</th></tr></thead><tbody>{payloads.length ? payloads.map((row: any) => <tr key={row.id}><td>{new Date(row.created_at).toLocaleString()}</td><td>{row.applicant_name || "Not found"}</td><td>{row.dob || "Not found"}</td><td>{row.report_id || "Not found"}</td><td>{row.record_count || 0}</td><td><Link style={{ color: "#0f3b5f", fontWeight: 800 }} href={`/tazworks/payloads/${row.id}`}>View</Link></td></tr>) : <tr><td colSpan={6}>No sample payloads imported yet.</td></tr>}</tbody></table></section></main></>;
}
