import Link from "next/link";
import { AppHeader } from "@/components/AppHeader";
import { requireUser } from "@/lib/session";

export default async function QuickAnalyzePage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const user = await requireUser();
  const params = await searchParams;
  return <><AppHeader user={user} /><main className="container-shell"><div style={{ display: "flex", justifyContent: "space-between", gap: 16, marginBottom: 20 }}><div><h1 style={{ margin: "0 0 8px" }}>Quick Analyze</h1><p style={{ color: "#5d687b", margin: 0 }}>Paste search information and raw data. The system will review what should be shown to the client.</p></div><Link className="btn-secondary" href="/cases/new">Create Full Case Instead</Link></div>{params.error ? <p style={{ color: "#b42318", fontWeight: 700 }}>Analysis failed. Search type, name, and raw data are required.</p> : null}<form action="/api/analyze/quick" method="post" className="card" style={{ display: "grid", gap: 18, padding: 22 }}><label><span className="field-label">Search type</span><select className="field-input" name="review_type" required><option value="county_search">County Search</option><option value="national_crim">National Crim</option></select><div className="field-help">Choose whether you are reviewing a county search or a national criminal database hit.</div></label><label><span className="field-label">Name</span><textarea className="field-input" name="person_name" required style={{ minHeight: 80 }} placeholder="Paste the name exactly as provided." /></label><label><span className="field-label">Aliases</span><textarea className="field-input" name="aliases_text" style={{ minHeight: 100 }} placeholder="Paste aliases, AKAs, maiden names, alternate spellings, or leave blank." /></label><label><span className="field-label">Address information</span><textarea className="field-input" name="address_text" style={{ minHeight: 120 }} placeholder="Paste address history, current address, prior addresses, county/state info, or identifiers tied to addresses." /></label><label><span className="field-label">Raw data</span><textarea className="field-input" name="pasted_text" required placeholder="Paste the raw county search or National Crim result here." /></label><div className="card" style={{ background: "#f8fafc", padding: 16 }}><strong>What the analysis should answer</strong><ul style={{ lineHeight: 1.7, marginBottom: 0 }}><li>Should anything from the pasted data be shown to the client?</li><li>Is this a possible match, non-match, or needs more review?</li><li>Is county verification needed before showing the client?</li><li>What information appears reportable or should be held back?</li></ul></div><button className="btn-primary" type="submit">Analyze Client Display</button></form></main></>;
}
