import Link from "next/link";
import { AppHeader } from "@/components/AppHeader";
import { requireUser } from "@/lib/session";

export default async function QuickAnalyzePage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const user = await requireUser();
  const params = await searchParams;
  return <><AppHeader user={user} /><main className="container-shell"><div style={{ display: "flex", justifyContent: "space-between", gap: 16, marginBottom: 20 }}><div><h1 style={{ margin: "0 0 8px" }}>Quick Analyze</h1><p style={{ color: "#5d687b", margin: 0 }}>Paste information, get guidance, and save as a case only when needed.</p></div><Link className="btn-secondary" href="/cases/new">Create Full Case Instead</Link></div>{params.error ? <p style={{ color: "#b42318", fontWeight: 700 }}>Analysis failed. Check required fields.</p> : null}<form action="/api/analyze/quick" method="post" className="card" style={{ display: "grid", gap: 18, padding: 22 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 }}><label><span className="field-label">Review type</span><select className="field-input" name="review_type"><option value="criminal_court">Criminal Court Review</option><option value="national_database">National Database Review</option></select></label><label><span className="field-label">Record source</span><input className="field-input" name="source_type" placeholder="County court, national database, other" /></label><label><span className="field-label">Subject name</span><input className="field-input" name="person_name" required /></label><label><span className="field-label">DOB</span><input className="field-input" name="dob" /></label><label><span className="field-label">State</span><input className="field-input" name="state" /></label><label><span className="field-label">County</span><input className="field-input" name="county" /></label><label><span className="field-label">Case / reference number</span><input className="field-input" name="reference_number" /></label><label><span className="field-label">Charge</span><input className="field-input" name="charge" /></label><label><span className="field-label">Disposition</span><input className="field-input" name="disposition" /></label><label><span className="field-label">Disposition date</span><input className="field-input" name="disposition_date" /></label><label><span className="field-label">Sentence</span><input className="field-input" name="sentence" /></label></div><label><span className="field-label">Raw pasted text</span><textarea className="field-input" name="pasted_text" required /></label><button className="btn-primary" type="submit">Run Quick Analysis</button></form></main></>;
}
